### ISSUE TITLE
How is the F1 score in the article calculated?

### ISSUE THREAD

**Issue by xiaolizh1** [QwenLM/ProcessBench#1]
Is the F1 score in the article the F1 score of the binary classification task that calculates whether each step is correct?

**Comment by chujiezheng** [comment]
![image](https://github.com/user-attachments/assets/99097076-1f7c-4599-8811-dcb5663e07d6)

We calculate the accuracies on erroneous and correct samples, respectively, and additionally **compute their harmonic mean as the F1 score**.

**Comment by xiaolizh1** [comment]
What I mean is whether this way of calculating F1 is reasonable. There are data predicted as positive examples in both correct and erroneous samples. Is it a bit one-sided to only calculate the accuracy of each?

**Comment by chujiezheng** [comment]
This calculation is indeed not perfect. Our original intention was to use the F1 metric to balance two extreme behaviors of the model: being overly picky or overly conservative. 
- **Being overly conservative** typically leads to low accuracy on error samples but high accuracy on correct samples, which is fairly intuitive.
- **Being overly picky** results in low accuracy on correct samples, but it doesn't necessarily lead to high accuracy on error samples (since identifying specific steps is still required). However, based on our observations, there is a **correlation** between accuracy on error samples and overly picky behavior patterns, so we made this somewhat imprecise metric calculation.

Personally, I think it's difficult to characterize our task with a single metric, but readers/people might prefer to have such an all-encompassing number to summarize and compare model performance :)

**Comment by xiaolizh1** [comment]
OK, thank you for your patience.
